name: Pull Request Cleanup

on:
  pull_request_target:
    types:
      - closed

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env:
          GITHUB_CTX: ${{toJson(github)}}
        run: echo "$GITHUB_CTX"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
